#pragma once

#define MAKE_STR_HELPER(a_str) #a_str
#define MAKE_STR(a_str) MAKE_STR_HELPER(a_str)

#define WTYP_VERSION_MAJOR	1
#define WTYP_VERSION_MINOR	0
#define WTYP_VERSION_PATCH	0
#define WTYP_VERSION_BETA	0
#define WTYP_VERSION_VERSTRING	MAKE_STR(WTYP_VERSION_MAJOR) "." MAKE_STR(WTYP_VERSION_MINOR) "." MAKE_STR(WTYP_VERSION_PATCH) "." MAKE_STR(WTYP_VERSION_BETA)
